### ISSUE TITLE
[question] How did you implement the add torrent feature?

### ISSUE THREAD

**Issue by mattiapv** [usineur/go-debrid#8]
Hello, I'm reading the alldebrid documentation but there isn't any API for adding Torrents.  I don't know Go but from the site and from your code i can see is just a form with POST method. Can you help me to understand how alldebrid works for adding torrent via magnet? I would like to write a telegram bot for me only. Thanks!

**Comment by usineur** [comment]
Hi,

if I remember well, you have to POST a form to this url: http://upload.alldebrid.com/uploadtorrent.php

For magnets, the form must contain the following informations:

| Key | Value |
| --- | --- |
| uid | can be retrieve in the cookie generated at connection |
| domain | https://alldebrid.com/torrent/ |
| magnet | magnet link |
| submit | "Convert this torrent" |

**Comment by usineur** [comment]
And if something was wrong, you will get an error to this redirect url: https://alldebrid.com/torrent/?error=X where _X_ is an error number.

**Comment by mattiapv** [comment]
Thanks I tried with Postman and works! But it gives me a Status 200 also if I leave the magnet value empty, but is not so important since I'm sure I will pass all the values

**Comment by mattiapv** [comment]
I understood why I wasn't getting the https://alldebrid.com/torrent/?error=X redirect url. Because if you don't have cookies set inside the browser you get the home page. Since I was sending the POST request inside Postman I got back the homepage, without being logged in of course. I'll just make a check if all the keys have the value before sending the request. Thanks for the help. You can close.

**Comment by GhyslainBruno** [comment]
Hi folks, I'm starting an alldebrid implementation with one of my app right now. 
Since this endpoint is not documented in the API section, don't you guys think it's kinda risky to use it ? I don't understand why this feature is not proposed in the API... 

I mean, you don't even get the uid using the API :-/

**Comment by usineur** [comment]
Risky ? In which way ?

**Comment by GhyslainBruno** [comment]
(sorry for the delay)

Maybe "risky" was not the good word, but what I mean is that since it's not even documented the developers could, all of a sudden, delete or change this "API" since it's actually not part of the API... 

Anyway, I asked them why such a feature (adding torrents/magnet links etc...) was not implemented in their API, and they basically said that it will be done soon (but they don't know when they will implement it). 

Here is the ticket I'm talking about : https://forum.alldebrid.com/index.php?/topic/939-ajout-de-torrentmagnet-via-api/&do=findComment&comment=2747

I have a question which might not be asked at the good place in here : 
Do you (@usineur) use a dedicated server ? 
I personally do, and it's kinda tricky because Alldebrid don't authorize such thing (as they told me in the previous ticket), and the other debrider service I used to use (realdebrid) uses some quotas limits about that... 
So if you have an idea to bypass such limitation, I would love to hear it :-D
(what I'm thinking at the moment is paying personal VPN and use it with my dedicated server... not ideal but should do the tick).

**Comment by usineur** [comment]
Yeah, I'm aware about this limitation. I have a dedicated server too, but I don't use it for downloads.
I only use go-debrid on my homemade NAS.

**Comment by GhyslainBruno** [comment]
:-/ I made an application that streams downloads from realdebrid to a google drive account, but know it's kinda complicated to keep using it... I totally didn't about these limitations...
